name: EAS Build

on:
  push:
    branches: [main, develop]
    paths: ['apps/mobile/**']
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production
      branch:
        description: 'Branch to build (only for manual triggers)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eas-build:
    name: EAS Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ (github.ref == 'refs/heads/main' || github.event.inputs.profile == 'production') && 'production' || 'development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create eas.json if not exists
        run: |
          cd apps/mobile
          if [ ! -f eas.json ]; then
            cat > eas.json << EOF
            {
              "cli": {
                "version": ">= 12.0.0"
              },
              "build": {
                "development": {
                  "developmentClient": true,
                  "distribution": "internal"
                },
                "preview": {
                  "distribution": "internal",
                  "android": {
                    "buildType": "apk"
                  }
                },
                "production": {
                  "autoIncrement": true
                }
              },
              "submit": {
                "production": {}
              }
            }
            EOF
          fi

      - name: Build for Android
        if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || github.event_name == 'push'
        run: |
          cd apps/mobile
          # Determine build profile based on branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PROFILE="production"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            PROFILE="preview"
          else
            PROFILE="${{ github.event.inputs.profile || 'development' }}"
          fi
          eas build --platform android --profile $PROFILE --non-interactive
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Build for iOS
        if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all'
        run: |
          cd apps/mobile
          # Determine build profile based on branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PROFILE="production"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            PROFILE="preview"
          else
            PROFILE="${{ github.event.inputs.profile || 'development' }}"
          fi
          eas build --platform ios --profile $PROFILE --non-interactive
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
